INSERT INTO COUNTRY VALUES (COUNTRY_PK.NEXTVAL, 'UNITED STATES');
INSERT INTO COUNTRY VALUES (COUNTRY_PK.NEXTVAL, 'GERMANY');
INSERT INTO COUNTRY VALUES (COUNTRY_PK.NEXTVAL, 'BRAZIL');

INSERT INTO CUSTOMER VALUES (CUSTOMER_PK.NEXTVAL, 'TERSKINE', 'MYPASSWORD', 'TOM ERSKINE', 
	'123 MAIN ST; ODENTON, MD', '6784564565', '1111111111', 'TOM@EMAIL.COM', 'S', 1);
INSERT INTO CUSTOMER VALUES (CUSTOMER_PK.NEXTVAL, 'MWONG', 'HISPASSWORD', 'MAURICE WONG', 
	'111 MY ST', '2222222222', '1112223333', 'MAURICE@EMAIL.COM', 'G', 2);
	
INSERT INTO CATEGORY VALUES (CATEGORY_PK.NEXTVAL, 'ELECTRONICS');
INSERT INTO CATEGORY VALUES (CATEGORY_PK.NEXTVAL, 'CAMPING');

INSERT INTO ROLES VALUES (ROLES_PK.NEXTVAL, 'ROLE1');
INSERT INTO ROLES VALUES (ROLES_PK.NEXTVAL, 'ROLE2');

INSERT INTO EMPLOYEE VALUES (EMPLOYEE_PK.NEXTVAL, 'JSMITH', 'PASSWORD', 1, 'JAMES SMITH');
INSERT INTO EMPLOYEE VALUES (EMPLOYEE_PK.NEXTVAL, 'MMITCHELL', 'SPORTS', 2, 'MIKE MITCHELL');

INSERT INTO OFFER VALUES (OFFER_PK.NEXTVAL, 'S', 1, 1, '01-JAN-14', 5, 50, '50 PERCENT OFF');
INSERT INTO OFFER VALUES (OFFER_PK.NEXTVAL, 'G', 2, 2, '01-MAR-14', 8, 80, '80 PERCENT OFF');

INSERT INTO ORDERTABLE VALUES (ORDERTABLE_PK.NEXTVAL, 1, '02-JAN-14', 1, 10000, 0, 'P', 'ADDRESS');
INSERT INTO ORDERTABLE VALUES (ORDERTABLE_PK.NEXTVAL, 2, '02-MAR-14', NULL, 50000, 1000, 'C', 'PLACE');

INSERT INTO PRODUCTS VALUES (PRODUCTS_PK.NEXTVAL, 1, 2, 'PRODUCT1', 10000, 12, 5, 'A', 1);
INSERT INTO PRODUCTS VALUES (PRODUCTS_PK.NEXTVAL, 2, 1, 'PRODUCT2', 100000, 6, 10, 'A', 2);

INSERT INTO PROCUREMENT VALUES (PROCUREMENT_PK.NEXTVAL, 1, 1, 10);
INSERT INTO PROCUREMENT VALUES (PROCUREMENT_PK.NEXTVAL, 2, 2, 5);

INSERT INTO ITEM VALUES (ITEM_PK.NEXTVAL, 1, 1, 2);
INSERT INTO ITEM VALUES (ITEM_PK.NEXTVAL, 2, 2, 3);

INSERT INTO PROPOSEPRODUCT VALUES (PROPOSEPRODUCT_PK.NEXTVAL, 'PROPOSAL1', 1, 1, 1, 'P', NULL, NULL);
INSERT INTO PROPOSEPRODUCT VALUES (PROPOSEPRODUCT_PK.NEXTVAL, 'PROPOSAL2', 2, 2, 1, 'P', NULL, 5);

