
  CREATE TABLE "ROLES" 
   (	"ROLEID" NUMBER(2,0) NOT NULL ENABLE, 
	"ROLEDESCRIPTION" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE SEQUENCE roles_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
  
  
  CREATE TABLE "CATEGORY" 
   (	"CATEGORYID" NUMBER(2,0) NOT NULL ENABLE, 
	"CATEGORYNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	
	 CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CATEGORY_UK1" UNIQUE ("CATEGORYNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE SEQUENCE category_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
 

  CREATE TABLE "COUNTRY" 
   (	"COUNTRYID" NUMBER(2,0) NOT NULL ENABLE, 
	"COUNTRYNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("COUNTRYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
  CREATE SEQUENCE country_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
 

  CREATE TABLE "CUSTOMER" 
   (	"CUSTOMERID" NUMBER(4,0) NOT NULL ENABLE, 
	"USERID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"RESIDENTPHONENUMBER" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"MOBILENUMBER" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"EMAILID" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"TYPE" CHAR(1 BYTE) DEFAULT 'S' NOT NULL ENABLE, 
	"COUNTRYID" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CUSTOMER_UK1" UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CUSTOMER_FK1" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "COUNTRY" ("COUNTRYID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CUSTOMER"."TYPE" IS 'S (silver), G (gold), P (platinum)';
   
   CREATE SEQUENCE customer_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
 

  CREATE TABLE "EMPLOYEE" 
   (	"EMPLOYEEID" NUMBER(3,0) NOT NULL ENABLE, 
	"USERID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ROLEID" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	
	 CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("EMPLOYEEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "EMPLOYEE_UK1" UNIQUE ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "EMPLOYEE_FK1" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "ROLES" ("ROLEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE SEQUENCE employee_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
 

  
 

  CREATE TABLE "OFFER" 
   (	"OFFERID" NUMBER(4,0) NOT NULL ENABLE, 
	"TYPE" CHAR(1 BYTE), 
	"COUNTRYID" NUMBER(2,0), 
	"EMPLOYEEID" NUMBER(3,0) NOT NULL ENABLE, 
	"LAUNCHDATE" DATE DEFAULT Sysdate NOT NULL ENABLE, 
	"VALIDITY" NUMBER(2,0) NOT NULL ENABLE, 
	"DISCOUNT" NUMBER(2,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "OFFER_PK" PRIMARY KEY ("OFFERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "OFFER_FK1" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "COUNTRY" ("COUNTRYID") ENABLE, 
	 CONSTRAINT "OFFER_FK2" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "OFFER"."TYPE" IS 'S (silver), G (gold), P (platinum)';
   
   CREATE SEQUENCE offer_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
 

  CREATE TABLE "ORDERTABLE" 
   (	"ORDERID" NUMBER(5,0) NOT NULL ENABLE, 
	"CUSTOMERID" NUMBER(4,0) NOT NULL ENABLE, 
	"ORDERDATE" DATE NOT NULL ENABLE, 
	"OFFERID" NUMBER(4,0), 
	"TOTALAMOUNT" NUMBER(12,0) NOT NULL ENABLE, 
	"AMOUNTPAID" NUMBER(12,0) NOT NULL ENABLE, 
	"STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"SHIPPINGADDRESS" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERTABLE_PK" PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ORDERTABLE_FK1" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "CUSTOMER" ("CUSTOMERID") ENABLE, 
	 CONSTRAINT "ORDERTABLE_FK2" FOREIGN KEY ("OFFERID")
	  REFERENCES "OFFER" ("OFFERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "ORDERTABLE"."AMOUNTPAID" IS 'Default to Total Amount';
   COMMENT ON COLUMN "ORDERTABLE"."STATUS" IS 'C (cleared), P (pending)';
   
   CREATE SEQUENCE ordertable_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;



  CREATE TABLE "PRODUCTS" 
   (	"PRODUCTID" NUMBER(3,0) NOT NULL ENABLE, 
	"CATEGORYID" NUMBER(2,0) NOT NULL ENABLE, 
	"EMPLOYEEID" NUMBER(3,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COST" NUMBER(10,0) NOT NULL ENABLE, 
	"WARRANTYPERIOD" NUMBER(2,0) NOT NULL ENABLE, 
	"STOCK" NUMBER(4,0) NOT NULL ENABLE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'A' NOT NULL ENABLE, 
	"REORDERLEVEL" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PRODUCTS_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PRODUCTS_FK1" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "CATEGORY" ("CATEGORYID") ENABLE, 
	 CONSTRAINT "PRODUCTS_FK2" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PRODUCTS"."STATUS" IS 'A (active), R (retired)';
   
   CREATE SEQUENCE products_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

   
CREATE TABLE "ITEM" 
   (	"ITEMID" NUMBER(5,0) NOT NULL ENABLE, 
	"ORDERID" NUMBER(5,0) NOT NULL ENABLE, 
	"PRODUCTID" NUMBER(3,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ITEM_FK1" FOREIGN KEY ("ORDERID")
	  REFERENCES "ORDERTABLE" ("ORDERID") ENABLE, 
	 CONSTRAINT "ITEM_FK2" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE SEQUENCE item_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
  
  
  CREATE TABLE "PROCUREMENT" 
   (	"PROCUREMENTID" NUMBER(3,0) NOT NULL ENABLE, 
	"PRODUCTID" NUMBER(3,0) NOT NULL ENABLE, 
	"EMPLOYEEID" NUMBER(3,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PROCUREMENT_PK" PRIMARY KEY ("PROCUREMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PROCUREMENT_FK1" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "PRODUCTS" ("PRODUCTID") ENABLE, 
	 CONSTRAINT "PROCUREMENT_FK2" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
CREATE SEQUENCE procurement_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;
 

  CREATE TABLE "PROPOSEPRODUCT" 
   (	"PROPOSALID" NUMBER(4,0) NOT NULL ENABLE, 
	"PRODUCTNAME" VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	"CUSTOMERID" NUMBER(4,0) NOT NULL ENABLE, 
	"CATEGORYID" NUMBER(2,0) NOT NULL ENABLE, 
	"VOTES" NUMBER(2,0) DEFAULT 1 NOT NULL ENABLE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'P' NOT NULL ENABLE, 
	"EMPLOYEEID" NUMBER(3,0), 
	"QUANTITY" NUMBER(3,0), 
	 CONSTRAINT "PROPOSEPRODUCT_PK" PRIMARY KEY ("PROPOSALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PROPOSEPRODUCT_UK1" UNIQUE ("PRODUCTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PROPOSEPRODUCT_FK1" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "CUSTOMER" ("CUSTOMERID") ENABLE, 
	 CONSTRAINT "PROPOSEPRODUCT_FK2" FOREIGN KEY ("CATEGORYID")
	  REFERENCES "CATEGORY" ("CATEGORYID") ENABLE, 
	 CONSTRAINT "PROPOSEPRODUCT_FK3" FOREIGN KEY ("EMPLOYEEID")
	  REFERENCES "EMPLOYEE" ("EMPLOYEEID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "PROPOSEPRODUCT"."VOTES" IS '1';
   COMMENT ON COLUMN "PROPOSEPRODUCT"."STATUS" IS 'P (proposed), A (accepted), R (rejected)';
 
CREATE SEQUENCE proposeproduct_pk
  START WITH 1
  INCREMENT BY 1
  CACHE 100;

