drop table roles cascade constraints purge;
drop sequence roles_pk;
drop table category cascade constraints purge;
drop sequence category_pk;
drop table country cascade constraints purge;
drop sequence country_pk;
drop table customer cascade constraints purge;
drop sequence customer_pk;
drop table employee cascade constraints purge;
drop sequence employee_pk;
drop table offer cascade constraints purge;
drop sequence offer_pk;
drop table ordertable cascade constraints purge;
drop sequence ordertable_pk;
drop table products cascade constraints purge;
drop sequence products_pk;
drop table item cascade constraints purge;
drop sequence item_pk;
drop table procurement cascade constraints purge;
drop sequence procurement_pk;
drop table proposeproduct cascade constraints purge;
drop sequence proposeproduct_pk;